#!/bin/bash

############################# Functions #######################################
#  usage
usage() {
  cat <<-EOF >&2
  send patchs ;
    usage: ./${0##*/} -v 0 [-n numberl] [-t title] [m commits string]
      -l  email list
      -f  folder which include patch files
      -h  help
    example:
      ./${0##*/} -m 0 -s ~/scan
EOF
  echo ""
  exit 0
}

# check options
folder="./"
maillist=""
mailfile=""

OPTIND=1
while getopts :f:l:dh arg; do
	case $arg in
		f)
			mailfile="$OPTARG";;
		l)
			maillist="$OPTARG";;
		d)
			folder="$OPTARG";;
		h)
			usage;;
		*)
			echo "wrong parameter list $arg"
			exit 1
			;;
	esac
done

if [ ! -d ${folder} ]; then
	echo "==============No folder:${folder} ======"
	exit 0
fi

cd ${folder}
ls ./* -l

#exit 0

files=$(ls 0*.patch)

for file in $files; do
  result=""
  num=""
  check=""

  num=$(echo "$file" | cut -d '-' -f 1)
  result=$(ls ${num}* | wc -l)

  [[ "$result" == "1" ]] || {
    check=$(ls -1 ${num}*)
    echo "$file: $num files not only 1: $check"
  exit
  }

  [[ -f /tmp/$file ]] && diff /tmp/$file $file && {
    echo "The same patch /tmp/$file already exists"
    exit
  }
done

filecmt=""
if [ -e ./maillist ]; then
	filecmt=`cat ./maillist`
fi
recvList="Zhang Weihong <weihong.zhang@intel.com>,weihong <weihong.zhang@linux.intel.com>,${maillist},${filecmt}"

#recvList="${recvList},Zhang Weihong <weihong.zhang@linux.intel.com>"
#recvList="${recvList},Kirill A. Shutemov <kirill.shutemov@linux.intel.com>"
#recvList="${recvList},Zhang li <li4.zhang@intel.com>"
#recvList="${recvList},Su heng <heng.su@intel.com>"

echo "${recvList}"

sleep 5
echo "git send-email -q --confirm=never --no-signed-off-by-cc --no-chain-reply-to --to=xxx $files"
git send-email	-q \
  --confirm=never \
  --no-signed-off-by-cc \
  --suppress-cc=all \
  --no-chain-reply-to \
  --to="${recvList}" \
  $files

patchdir=patch-`date +%y%m%d-%N`
mkdir ./${patchdir}
cp ${files} ./${patchdir}/
echo "Move patches into ./${patchdir}"

